export const ARTISTS_BY_STYLE = {
  Realism: [
    'Gustave Courbet',
    'Jean-François Millet',
    'Ilya Repin',
    'Honoré Daumier',
    'Winslow Homer',
    'Thomas Eakins',
    'Johannes Vermeer',
    'Diego Velázquez',
    'Francisco Goya',
    'J. M. W. Turner',
    'John Singer Sargent',
    'Richard Estes',
  ],
  Impressionism: [
    'Georges Seurat',
    'Paul Cézanne',
    'Claude Monet',
    'Pierre-Auguste Renoir',
    'Edgar Degas',
    'Camille Pissarro',
    'Berthe Morisot',
    'Mary Cassatt',
    'David Hockney',
  ],
  Expressionism: [
    'Edvard Munch',
    'Vincent van Gogh',
    'Wassily Kandinsky',
    'Egon Schiele',
    'Ernst Ludwig Kirchner',
    'Emil Nolde',
    'Paula Modersohn-Becker',
    'Jean-Michel Basquiat',
  ],
  'Abstract Art': [
    'Wassily Kandinsky',
    'Piet Mondrian',
    'Mark Rothko',
    'Kazimir Malevich',
    'Jackson Pollock',
    'Joan Miró',
    'Helen Frankenthaler',
    'Gustav Klimt',
    'Robert Delaunay',
  ],
} as const;

export type StyleKey = keyof typeof ARTISTS_BY_STYLE;
